server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: specialty-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/specialties/**

        - id: doctor-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/appointments/**

        - id: summary-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/summary/**

logging:
  level:
    root: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL where Eureka Server is running
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

