server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: specialty-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/specialties/**

        - id: doctor-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/appointments/**

        - id: summary-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/summary/**
